# The content below is copied from the esp-docs repo

# -*- coding: utf-8 -*-
#
# English Language RTD & Sphinx config file
#
# Uses ../conf_common.py for most non-language-specific settings.

# Importing conf_common adds all the non-language-specific
# parts to this conf module

try:
    from conf_common import *  # noqa: F403,F401
except ImportError:
    import os
    import sys
    sys.path.insert(0, os.path.abspath('../'))
    from conf_common import *  # noqa: F403,F401

import datetime

current_year = datetime.datetime.now().year

# General information about the project.
project = u'ESP Product Security'
copyright = u'2024 - {}, Espressif Systems (Shanghai) Co., Ltd'.format(current_year)
pdf_title = u'ESP Product Security Handbook'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
language = 'en'

# doc_id = {'esp32': '4089', 'esp32s2': '4422', 'esp32s3': '5419', 'esp32c2': '5726', 'esp32c3': '5084', 'esp32c6': '6511', 'esp32h2': '6715', 'esp32c5': '8823'}

# Chatbot widget configuration
html_js_files = ['js/chatbot_widget_en.js']
